#!/usr/bin/env python3
#
#   Pesquisa de vídeos via terminal
#   @utor soneca
#

import sys

if( len(sys.argv)!=2 ):
	print("Uso: "+sys.argv[0]+" \'sua pesquisa\'");
	exit();

import requests, string
from colorama import Fore,Back,Style
from bs4 import BeautifulSoup


search_term= sys.argv[1].replace(" ", "+");
print("Disparando requisição! :: "+"https://invidio.us/search?q="+search_term);
headers={"User-agent" : "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/71.0"};
r = requests.get("https://invidio.us/search?q="+search_term);
r.encoding="unicode";

soup = BeautifulSoup(r.text, "lxml");
soup = soup.find_all("div", class_="pure-g")[2];

for video in soup.find_all("div", class_="h-box"):
	print( "-------------" );
	#print( video );
	try: #NOME DO CANAL
		canal = video.find_all("a")[2];
		print( canal.text );
	except:
		pass;
	try:
		titulo = video.find_all("a")[1];
		views = video.find("div", class_="pure-u-1-3").text.strip();
		print( Style.BRIGHT+Fore.GREEN+titulo.text.strip()+Style.RESET_ALL+" ["+video.p.text+"]"+" | "+Fore.CYAN+views+Style.RESET_ALL );
		print( Fore.YELLOW+"https://invidio.us"+titulo["href"]+Style.RESET_ALL );
		print( Fore.YELLOW+"https://youtube.com"+titulo["href"]+Style.RESET_ALL );
	except:
		pass;
