#!/bin/bash

if [ -z $1 ]
then
	echo -e "\e[31mUso: $0 [-audio|-video]\e[0m"
	exit 0;
fi

if [ $1 == "-audio" ]; then
	qualidade="251" #só audio
else
	qualidade="18" #qualidade média
	#qualidade="22" #qualidade alta
fi

info="[\e[32mINFO\e[0m]"
erro="[\e[31mERRO\e[0m]"

## Informação sobre padrão de url
echo -e "$info Tipo de url:"
echo -e "$info\t~> \e[33m/watch?v=(id do vídeo)\e[0m"

##  Recebe url
echo -n -e "$info Cole a url: ";
read url

## Confere a url
if [[ $(echo "$url" | grep -o "/watch?v=") == "/watch?v=" ]]
then
	# "Url correta!"
	vid=$(echo "$url" | sed "s/.*\/watch?v=//"| sed "s/\&.*$//")
else
	# "Url incorreta!"
	echo -e "$erro Url não compreendida"
	exit 0;
fi
echo -e "$info ID do vídeo... \e[93m$vid\e[0m"

## Requisita link de streaming
instancias=(	"https://invidious.zapashcanon.fr"
				"https://invidious.fdn.fr"
				"https://invidious.snopyta.org"
				"https://invidiou.site"
				"https://invidious.kavin.rocks"
				"https://invidious.fdn.fr"
				"https://invidious.xyz"
				"https://invidiou.site"
				"https://tube.connect.cafe"
			);
for instancia in ${instancias[*]}
do
	link_req="$instancia/latest_version?id=$vid&itag=$qualidade"
	echo -e "$info Requisitando: \e[33m$link_req\e[0m"
	url=$(proxychains -q curl -i $link_req 2>/dev/null |grep -i "location: " |sed "s/location: //" )

	#Se já achou a url, sai do loop
	if [ ! -z "$url" ]; then
		break;
	fi
done


## Se não conseguiu o link de streaming na primeira instância
if [ -z "$url" ]
then
	instancia="https://invidious.glie.town"
	link_req="$instancia/latest_version?id=$vid&itag=$qualidade"
	echo -e "$info Requisitando: \e[33m$link_req\e[0m"
	url=$(proxychains -q curl -i $link_req 2>/dev/null \
	 |grep -i "location: " \
	 |sed "s/location: //")
fi

##
if [ -z "$url" ]
then
	echo -e "$erro Sem link de stream disponível"
	exit 1
fi

echo -e "$info url: \e[2;96m$url\e[0m"

if [ $1 == "-audio" ]
then
	echo -e "$info \e[33mRecebendo áudio...\e[0m"
	proxychains -q mplayer -cache 2048 $url 2>/dev/null #-vo null (anularia video output que não tem com itag=251)
elif [ $1 == "-video" ]
then
	echo -e "$info \e[33mRecebendo vídeo...\e[0m"
	proxychains -q mplayer -cache 10000 $url 2>/dev/null
fi
